# Generated by Django 3.1.7 on 2021-04-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=300, null=True)),
                ('dob', models.DateField()),
                ('company', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
